spring:
  application:
    name: spring-cloud-alibaba-service-gateway
  cloud:
    nacos:
      discovery:
        namespace: spring-cloud-alibaba
        group: PROD_GROUP
        cluster-name: hangzhou # 集群隔离
        ephemeral: true # 持久化实例 ture为临时实例 false为持久化实例 临时实例发生异常直接剔除, 而持久化实例等待恢复
    loadbalancer: # loadbalancer 开启 nacos 支持，集成 nacos 负载均衡
      nacos:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: spring-cloud-alibaba-auth
          uri: lb://spring-cloud-alibaba-service-auth
          predicates:
            - Path=/auth/**
        - id: spring-cloud-alibaba-rocketmq
          uri: lb://spring-cloud-alibaba-service-rocketmq
          predicates:
            - Path=/rocketmq/**
        - id: spring-cloud-alibaba-storage
          uri: lb://spring-cloud-alibaba-service-storage
          predicates:
            - Path=/storage/**
        - id: spring-cloud-alibaba-order
          uri: lb://spring-cloud-alibaba-service-order
          predicates:
            - Path=/order/**
        - id: spring-cloud-alibaba-account
          uri: lb://spring-cloud-alibaba-service-account
          predicates:
            - Path=/account/**
        - id: spring-cloud-alibaba-pay
          uri: lb://spring-cloud-alibaba-service-pay
          predicates:
            - Path=/pay/**
        - id: spring-cloud-alibaba-logistics
          uri: lb://spring-cloud-alibaba-service-logistics
          predicates:
            - Path=/logistics/**
    sentinel:
      eager: true  # 是否饥饿加载。默认为 false 关闭
      transport:
        dashboard: 127.0.0.1:8080  # Sentinel 控制台默认启动在 8080 端口
      filter:
        enabled: false
      datasource:
        ds1-flow:
          nacos:
            serverAddr: http://nacos.liupeng.cloud
            dataId: ${spring.application.name}-flow-rules
            namespace: alibaba-sentinel
            groupId: SENTINEL_GROUP
            ruleType: FLOW
            dataType: json
      # 注释以下内容执行自定义 fallback
      scg:  # Sentinel 对 Spring Cloud Gateway 的专属配置项，对应 SentinelGatewayProperties 类
        order: -2147483648  # 过滤器顺序，默认为 -2147483648 最高优先级
        fallback:
          # fallback 模式，目前有三种：response、redirect、空（执行自定义 cloud.liupeng.sentinel.handler.CustomBlockRequestHandler 类）
          mode: response
          # 对应 response 模式
          response-status: 429
          # 响应内容，默认为空
          response-body: '{"code": 429, "message": "网关限流，请稍后重试！"}'
          content-type: application/json # 内容类型，默认为 application/json

          # 对应 redirect 模式
          #redirect: http://www.liupeng.cloud

      # 注释以上内容执行自定义 fallback
  mvc:
    throw-exception-if-no-handler-found: true  # 使用 SpringBoot 捕获 404 异常
  web:
    resources:
      add-mappings: true  # 静态资源的映射，默认为true，修改为false时禁止加载静态资源，加载自定义 404 异常。本项目在拦截器中定义404异常

server:
  port: 9527

logging:
  config:
    - classpath:log4j2.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"