spring:
  application:
    name: spring-cloud-alibaba-service-rocketmq
  cloud:
    nacos:
      discovery:
        namespace: spring-cloud-alibaba
        group: PROD_GROUP
        cluster-name: hangzhou # 集群隔离
        ephemeral: true # 持久化实例 ture为临时实例 false为持久化实例 临时实例发生异常直接剔除, 而持久化实例等待恢复
    loadbalancer: # loadbalancer 开启 nacos 支持，集成 nacos 负载均衡
      nacos:
        enabled: true
  mvc:
    throw-exception-if-no-handler-found: true  # 使用 SpringBoot 捕获 404 异常
  web:
    resources:
      add-mappings: true  # 静态资源的映射，默认为true，修改为false时禁止加载静态资源，加载自定义 404 异常。本项目在拦截器中定义404异常

server:
  port: 3020
  undertow:
    threads:  # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程 不要设置过大，如果过大，启动项目会报错：打开文件数过多
      io: 4  # 指定工作者线程的 I/0 线程数，默认为 2 或者 CPU 的个数
      worker: 256  # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    max-http-post-size: -1B  # 设置 HTTP POST 内容的最大长度，默认不做限制
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    buffers-per-region: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true

feign:
  sentinel:
    enabled: true

logging:
  config:
    - classpath:log4j2.xml